/* ============================================================
   ÁLBUM COPA 2026 — DADOS
   2 capa + 20 FIFA World Cup + 48 seleções × 20 = 982 figurinhas
   Edite à vontade: nomes, ordem e seleções.
   ============================================================ */

/* ---------- Capa (Coca-Cola) ---------- */
const COVER_SECTION = {
  id: "capa",
  code: "CC",
  name: "Capa",
  longName: "Capa & apresentação",
  flag: "🥤",
  stickers: [
    { code: "CC-1", name: "Capa Oficial" },
    { code: "CC-2", name: "Apresentação" },
  ],
};

/* ---------- FIFA World Cup ---------- */
const FWC_SECTION = {
  id: "fwc",
  code: "FWC",
  name: "FIFA World Cup",
  longName: "FIFA World Cup — história",
  flag: "🏆",
  stickers: [
    { code: "FWC-0", name: "Quadro de Honra" },
    { code: "FWC-1", name: "Slogan Oficial" },
    { code: "FWC-2", name: "Emblema Oficial" },
    { code: "FWC-3", name: "Mascote Oficial" },
    { code: "FWC-4", name: "Troféu Oficial" },
    { code: "FWC-5", name: "TRIONDA — Bola Oficial" },
    { code: "FWC-6", name: "Emblema Canadá" },
    { code: "FWC-7", name: "Emblema México" },
    { code: "FWC-8", name: "Emblema USA" },
    { code: "FWC-9", name: "Italy 1934" },
    { code: "FWC-10", name: "Brazil 1950" },
    { code: "FWC-11", name: "Switzerland 1954" },
    { code: "FWC-12", name: "Chile 1962" },
    { code: "FWC-13", name: "Germany 1974" },
    { code: "FWC-14", name: "Mexico 1986" },
    { code: "FWC-15", name: "USA 1994" },
    { code: "FWC-16", name: "Korea/Japan 2002" },
    { code: "FWC-17", name: "Germany 2006" },
    { code: "FWC-18", name: "Brazil 2014" },
    { code: "FWC-19", name: "Qatar 2022" },
  ],
};

/* ---------- Seleções (48) ----------
   Ordem: Grupos A → L (4 seleções por grupo).
   players[] tem 19 nomes nesta ordem:
     idx 0–10  → posições 2–12
     idx 11    → posição 13 (Team Photo)
     idx 12–17 → posições 14–19
     idx 18    → posição 20
   N-1 (Escudo) é fixo. */

const COUNTRIES = [
  /* ===== GRUPO A ===== */
  {
    id: "mex",
    code: "MEX",
    name: "México",
    flag: "🇲🇽",
    players: [
      "Luis Malagón",
      "Johan Vásquez",
      "Jorge Sánchez",
      "César Montes",
      "Jesús Gallardo",
      "Israel Reyes",
      "Diego Lainez",
      "Carlos Rodríguez",
      "Edson Álvarez",
      "Orbelín Pineda",
      "Marcel Ruíz",
      "Team Photo",
      "Érick Sánchez",
      "Hirving Lozano",
      "Santiago Giménez",
      "Raúl Jiménez",
      "Alexis Vega",
      "Roberto Alvarado",
      "César Huerta",
    ],
  },
  {
    id: "rsa",
    code: "RSA",
    name: "África do Sul",
    flag: "🇿🇦",
    players: [
      "Ronwen Williams",
      "Sipho Chaine",
      "Aubrey Modiba",
      "Samukelo Kabini",
      "Mbekezeli Mbokazi",
      "Khulumani Ndamane",
      "Siyabonga Ngezana",
      "Khuliso Mudau",
      "Nkosinathi Sibisi",
      "Teboho Mokoena",
      "Thalente Mbatha",
      "Team Photo",
      "Bathusi Aubaas",
      "Yaya Sithole",
      "Sipho Mbule",
      "Lyle Foster",
      "Iqraam Rayners",
      "Mohau Nkota",
      "Oswin Appolis",
    ],
  },
  {
    id: "kor",
    code: "KOR",
    name: "Coreia do Sul",
    flag: "🇰🇷",
    players: [
      "Hyeon-woo Jo",
      "Seung-Gyu Kim",
      "Min-jae Kim",
      "Yu-min Cho",
      "Young-woo Seol",
      "Han-beom Lee",
      "Tae-seok Lee",
      "Myung-jae Lee",
      "Jae-sung Lee",
      "In-beom Hwang",
      "Kang-in Lee",
      "Team Photo",
      "Seung-ho Paik",
      "Jens Castrop",
      "Dong-gyeong Lee",
      "Gue-sung Cho",
      "Heung-min Son",
      "Hee-chan Hwang",
      "Hyeon-Gyu Oh",
    ],
  },
  {
    id: "cze",
    code: "CZE",
    name: "República Tcheca",
    flag: "🇨🇿",
    players: [
      "Matěj Kovář",
      "Jindřich Staněk",
      "Ladislav Krejčí",
      "Vladimír Coufal",
      "Jaroslav Zelený",
      "Tomáš Holeš",
      "David Zima",
      "Michal Sadílek",
      "Lukáš Provod",
      "Lukáš Červ",
      "Tomáš Souček",
      "Team Photo",
      "Pavel Šulc",
      "Matěj Vydra",
      "Vasil Kušej",
      "Tomáš Chorý",
      "Václav Černý",
      "Adam Hložek",
      "Patrik Schick",
    ],
  },

  /* ===== GRUPO B ===== */
  {
    id: "can",
    code: "CAN",
    name: "Canadá",
    flag: "🇨🇦",
    players: [
      "Dayne St. Clair",
      "Alphonso Davies",
      "Alistair Johnston",
      "Samuel Adekugbe",
      "Richie Laryea",
      "Derek Cornelius",
      "Moïse Bombito",
      "Kamal Miller",
      "Stephen Eustáquio",
      "Ismaël Koné",
      "Jonathan Osorio",
      "Team Photo",
      "Jacob Shaffelburg",
      "Mathieu Choinière",
      "Niko Sigur",
      "Tajon Buchanan",
      "Liam Millar",
      "Cyle Larin",
      "Jonathan David",
    ],
  },
  {
    id: "bih",
    code: "BIH",
    name: "Bósnia e Herzegovina",
    flag: "🇧🇦",
    players: [
      "Nikola Vasilj",
      "Amar Dedić",
      "Sead Kolašinac",
      "Tarik Muharemović",
      "Nihad Mujakić",
      "Nikola Katić",
      "Amir Hadžiahmetović",
      "Benjamin Tahirović",
      "Armin Gigović",
      "Ivan Šunjić",
      "Ivan Bašić",
      "Team Photo",
      "Dženis Burnić",
      "Esmir Bajraktarević",
      "Amar Memić",
      "Ermedin Demirović",
      "Edin Džeko",
      "Samed Baždar",
      "Haris Tabaković",
    ],
  },
  {
    id: "qat",
    code: "QAT",
    name: "Catar",
    flag: "🇶🇦",
    players: [
      "Meshaal Barsham",
      "Sultan Albrake",
      "Lucas Mendes",
      "Homam Ahmed",
      "Boualem Khoukhi",
      "Pedro Miguel",
      "Tarek Salman",
      "Mohamed Al-Mannai",
      "Karim Boudiaf",
      "Assim Madibo",
      "Ahmed Fatehi",
      "Team Photo",
      "Mohammed Waad",
      "Abdulaziz Hatem",
      "Hassan Al-Haydos",
      "Edmilson Junior",
      "Akram Hassan Afif",
      "Ahmed Al Ganehi",
      "Almoez Ali",
    ],
  },
  {
    id: "sui",
    code: "SUI",
    name: "Suíça",
    flag: "🇨🇭",
    players: [
      "Gregor Kobel",
      "Yvon Mvogo",
      "Manuel Akanji",
      "Ricardo Rodríguez",
      "Nico Elvedi",
      "Aurèle Amenda",
      "Silvan Widmer",
      "Granit Xhaka",
      "Denis Zakaria",
      "Remo Freuler",
      "Fabian Rieder",
      "Team Photo",
      "Ardon Jashari",
      "Johan Manzambi",
      "Michel Aebischer",
      "Breel Embolo",
      "Ruben Vargas",
      "Dan Ndoye",
      "Zeki Amdouni",
    ],
  },

  /* ===== GRUPO C ===== */
  {
    id: "bra",
    code: "BRA",
    name: "Brasil",
    flag: "🇧🇷",
    players: [
      "Alisson",
      "Bento",
      "Marquinhos",
      "Éder Militão",
      "Gabriel Magalhães",
      "Danilo",
      "Wesley",
      "Lucas Paquetá",
      "Casemiro",
      "Bruno Guimarães",
      "Luiz Henrique",
      "Team Photo",
      "Vinícius Júnior",
      "Rodrygo",
      "João Pedro",
      "Matheus Cunha",
      "Gabriel Martinelli",
      "Raphinha",
      "Estêvão",
    ],
  },
  {
    id: "mar",
    code: "MAR",
    name: "Marrocos",
    flag: "🇲🇦",
    players: [
      "Yassine Bounou",
      "Munir El Kajoui",
      "Achraf Hakimi",
      "Noussair Mazraoui",
      "Nayef Aguerd",
      "Romain Saïss",
      "Jawad El Yamiq",
      "Adam Masina",
      "Sofyan Amrabat",
      "Azzedine Ounahi",
      "Eliesse Ben Seghir",
      "Team Photo",
      "Bilal El Khannouss",
      "Ismael Saibari",
      "Youssef En-Nesyri",
      "Abde Ezzalzouli",
      "Soufiane Rahimi",
      "Brahim Diaz",
      "Ayoub El Kaabi",
    ],
  },
  {
    id: "hai",
    code: "HAI",
    name: "Haiti",
    flag: "🇭🇹",
    players: [
      "Johny Placide",
      "Carlens Arcus",
      "Martin Expérience",
      "Jean-Kevin Duverne",
      "Ricardo Adé",
      "Duke Lacroix",
      "Garven Metusala",
      "Hannes Delcroix",
      "Leverton Pierre",
      "Danley Jean Jacques",
      "Jean-Ricner Bellegarde",
      "Team Photo",
      "Christopher Attys",
      "Derrick Etienne Jr.",
      "Josué Casimir",
      "Ruben Providence",
      "Duckens Nazon",
      "Louicius Deedson",
      "Frantzdy Pierrot",
    ],
  },
  {
    id: "sco",
    code: "SCO",
    name: "Escócia",
    flag: "🏴\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
    players: [
      "Angus Gunn",
      "Jack Hendry",
      "Kieran Tierney",
      "Aaron Hickey",
      "Andrew Robertson",
      "Scott McKenna",
      "John Souttar",
      "Anthony Ralston",
      "Grant Hanley",
      "Scott McTominay",
      "Billy Gilmour",
      "Team Photo",
      "Lewis Ferguson",
      "Ryan Christie",
      "Kenny McLean",
      "John McGinn",
      "Lyndon Dykes",
      "Che Adams",
      "Ben Gannon-Doak",
    ],
  },

  /* ===== GRUPO D ===== */
  {
    id: "usa",
    code: "USA",
    name: "Estados Unidos",
    flag: "🇺🇸",
    players: [
      "Math Freese",
      "Chris Richards",
      "Tim Ream",
      "Mark McKenzie",
      "Alex Freeman",
      "Antonee Robinson",
      "Tyler Adams",
      "Tanner Tessmann",
      "Weston McKennie",
      "Christian Roldan",
      "Timothy Weah",
      "Team Photo",
      "Diego Luna",
      "Malim Tillman",
      "Christian Pulisic",
      "Brenden Aaronson",
      "Ricardo Pepi",
      "Haji Wright",
      "Folarin Balogun",
    ],
  },
  {
    id: "par",
    code: "PAR",
    name: "Paraguai",
    flag: "🇵🇾",
    players: [
      "Roberto Fernández",
      "Orlando Gill",
      "Gustavo Gómez",
      "Fabián Balbuena",
      "Juan José Cáceres",
      "Omar Alderete",
      "Junior Alonso",
      "Mathías Villasanti",
      "Diego Gómez",
      "Damián Bobadilla",
      "Andrés Cubas",
      "Team Photo",
      "Matías Galarza Fonda",
      "Julio Enciso",
      "Alejandro Romero Gamarra",
      "Miguel Almirón",
      "Ramón Sosa",
      "Ángel Romero",
      "Antonio Sanabría",
    ],
  },
  {
    id: "aus",
    code: "AUS",
    name: "Austrália",
    flag: "🇦🇺",
    players: [
      "Mathew Ryan",
      "Joe Gauci",
      "Harry Souttar",
      "Alessandro Circati",
      "Jordan Bos",
      "Aziz Behich",
      "Cameron Burgess",
      "Lewis Miller",
      "Milos Degenek",
      "Jackson Irvine",
      "Riley McGree",
      "Team Photo",
      "Aiden O'Neill",
      "Connor Metcalfe",
      "Patrick Yazbek",
      "Craig Goodwin",
      "Kusini Yengi",
      "Nestory Irankunda",
      "Mohamed Touré",
    ],
  },
  {
    id: "tur",
    code: "TUR",
    name: "Turquia",
    flag: "🇹🇷",
    players: [
      "Ugurcan Cakir",
      "Mert Muldur",
      "Zeki Celik",
      "Abdulkerim Bardakci",
      "Caglar Soyunku",
      "Merih Demiral",
      "Ferdi Kadioglu",
      "Kaan Ayhan",
      "Ismail Yuksek",
      "Hakan Calhanoglu",
      "Orkun Kokcu",
      "Team Photo",
      "Arda Güler",
      "Irfan Can Kahvecu",
      "Yunus Akgun",
      "Can Uzun",
      "Baris Alper Yilmaz",
      "Kerem Akturkoglu",
      "Kenan Yildiz",
    ],
  },

  /* ===== GRUPO E ===== */
  {
    id: "ger",
    code: "GER",
    name: "Alemanha",
    flag: "🇩🇪",
    players: [
      "Marc-André ter Stegen",
      "Jonathan Tah",
      "David Raum",
      "Nico Schlotterbeck",
      "Antonio Rüdiger",
      "Waldemar Anton",
      "Ridle Baku",
      "Maximilian Mittelstädt",
      "Joshua Kimmich",
      "Florian Wirtz",
      "Felix Nmecha",
      "Team Photo",
      "Leon Goretzka",
      "Jamal Musiala",
      "Serge Gnabry",
      "Kai Havertz",
      "Leroy Sané",
      "Karim Adeyemi",
      "Nick Woltemade",
    ],
  },
  {
    id: "cuw",
    code: "CUW",
    name: "Curaçao",
    flag: "🇨🇼",
    players: [
      "Eloy Room",
      "Armando Obispo",
      "Sherel Floranus",
      "Jurien Gaari",
      "Joshua Brenet",
      "Roshon Van Eijma",
      "Shurandy Sambo",
      "Livano Comenencia",
      "Godfried Roemeratoe",
      "Juninho Bacuna",
      "Leandro Bacuna",
      "Team Photo",
      "Tahith Chong",
      "Kenji Gorré",
      "Jearl Margaritha",
      "Jurgen Locadia",
      "Jeremy Antonisse",
      "Gervane Kastaneer",
      "Sontje Hansen",
    ],
  },
  {
    id: "civ",
    code: "CIV",
    name: "Costa do Marfim",
    flag: "🇨🇮",
    players: [
      "Yahia Fofana",
      "Ghislain Konan",
      "Wilfried Singo",
      "Odilon Kossounou",
      "Evan Ndicka",
      "Willy Boly",
      "Emmanuel Agbadou",
      "Ousmane Diomande",
      "Franck Kessié",
      "Seko Fofana",
      "Ibrahim Sangaré",
      "Team Photo",
      "Jean-Philippe Gbamin",
      "Amad Diallo",
      "Sébastien Haller",
      "Simon Adingra",
      "Yan Diomande",
      "Evann Guessand",
      "Oumar Diakité",
    ],
  },
  {
    id: "ecu",
    code: "ECU",
    name: "Equador",
    flag: "🇪🇨",
    players: [
      "Hernán Galíndez",
      "Gonzalo Valle",
      "Piero Hincapié",
      "Pervis Estupiñán",
      "Willian Pacho",
      "Ángelo Preciado",
      "Joel Ordóñez",
      "Moisés Caicedo",
      "Alan Franco",
      "Kendry Páez",
      "Pedro Vite",
      "Team Photo",
      "John Yeboah",
      "Leonardo Campana",
      "Gonzalo Plata",
      "Nilson Angulo",
      "Alan Minda",
      "Kevin Rodríguez",
      "Enner Valencia",
    ],
  },

  /* ===== GRUPO F ===== */
  {
    id: "ned",
    code: "NED",
    name: "Holanda",
    flag: "🇳🇱",
    players: [
      "Bart Verbruggen",
      "Virgil van Dijk",
      "Micky van de Ven",
      "Jurriën Timber",
      "Denzel Dumfries",
      "Nathan Aké",
      "Jeremie Frimpong",
      "Jan Paul van Hecke",
      "Tijjani Reijnders",
      "Ryan Gravenberch",
      "Teun Koopmeiners",
      "Team Photo",
      "Frenkie de Jong",
      "Xavi Simons",
      "Justin Kluivert",
      "Memphis Depay",
      "Donyell Malen",
      "Wout Weghorst",
      "Cody Gakpo",
    ],
  },
  {
    id: "jpn",
    code: "JPN",
    name: "Japão",
    flag: "🇯🇵",
    players: [
      "Zion Suzuki",
      "Henry Heroki Mochizuki",
      "Ayumu Seko",
      "Junnosuke Suzuki",
      "Shogo Taniguchi",
      "Tsuyoshi Watanabe",
      "Kaishu Sano",
      "Yuki Soma",
      "Ao Tanaka",
      "Daichi Kamada",
      "Takefusa Kubo",
      "Team Photo",
      "Ritsu Doan",
      "Keito Nakamura",
      "Takumi Minamino",
      "Shuto Machino",
      "Junya Ito",
      "Koki Ogawa",
      "Ayase Ueda",
    ],
  },
  {
    id: "swe",
    code: "SWE",
    name: "Suécia",
    flag: "🇸🇪",
    players: [
      "Victor Johansson",
      "Isak Hien",
      "Gabriel Gudmundsson",
      "Emil Holm",
      "Victor Nilsson Lindelöf",
      "Gustaf Lagerbielke",
      "Lucas Bergvall",
      "Hugo Larsson",
      "Jesper Karlström",
      "Yasin Ayari",
      "Mattias Svanberg",
      "Team Photo",
      "Daniel Svensson",
      "Ken Sema",
      "Roony Bardghji",
      "Dejan Kulusevski",
      "Anthony Elanga",
      "Alexander Isak",
      "Viktor Gyökeres",
    ],
  },
  {
    id: "tun",
    code: "TUN",
    name: "Tunísia",
    flag: "🇹🇳",
    players: [
      "Bechir Ben Said",
      "Aymen Dahmen",
      "Van Valery",
      "Montassar Talbi",
      "Yassine Meriah",
      "Ali Abdi",
      "Dylan Bronn",
      "Ellyes Skhiri",
      "Aissa Laidouni",
      "Ferjani Sassi",
      "Mohamed Ali Ben Romdhane",
      "Team Photo",
      "Hannibal Mejbri",
      "Elias Achouri",
      "Elias Saad",
      "Hazem Mastouri",
      "Ismael Gharbi",
      "Sayfallah Ltaief",
      "Naim Sliti",
    ],
  },

  /* ===== GRUPO G ===== */
  {
    id: "bel",
    code: "BEL",
    name: "Bélgica",
    flag: "🇧🇪",
    players: [
      "Thibaut Courtois",
      "Arthur Theate",
      "Timothy Castagne",
      "Zeno Debast",
      "Brandon Mechele",
      "Maxim De Cuyper",
      "Thomas Meunier",
      "Youri Tielemans",
      "Amadou Onana",
      "Nicolas Raskin",
      "Alexis Saelemaekers",
      "Team Photo",
      "Hans Vanaken",
      "Kevin De Bruyne",
      "Jérémy Doku",
      "Charles De Ketelaere",
      "Leandro Trossard",
      "Loïs Openda",
      "Romelu Lukaku",
    ],
  },
  {
    id: "egy",
    code: "EGY",
    name: "Egito",
    flag: "🇪🇬",
    players: [
      "Mohamed El Shenawy",
      "Mohamed Hany",
      "Mohamed Hamdy",
      "Yasser Ibrahim",
      "Khaled Sobhi",
      "Ramy Rabia",
      "Hossam Abdelmaguid",
      "Ahmed Fatouh",
      "Marwan Attia",
      "Zizo",
      "Hamdy Fathy",
      "Team Photo",
      "Mohamed Lasheen",
      "Emam Ashour",
      "Osama Faisal",
      "Mohamed Salah",
      "Mostafa Mohamed",
      "Trezeguet",
      "Omar Marmoush",
    ],
  },
  {
    id: "irn",
    code: "IRN",
    name: "Irã",
    flag: "🇮🇷",
    players: [
      "Alireza Beiranvand",
      "Morteza Pouraliganji",
      "Ehsan Hajsafi",
      "Milad Mohammadi",
      "Shoja Khalilzadeh",
      "Ramin Rezaeian",
      "Hossein Kanaani",
      "Sadegh Moharrami",
      "Saleh Hardani",
      "Saeed Ezatolahi",
      "Saman Ghoddos",
      "Team Photo",
      "Omid Noorafkan",
      "Roozbeh Cheshmi",
      "Mohammad Mohebi",
      "Sardar Azmoun",
      "Mehdi Taremi",
      "Alireza Jahanbakhsh",
      "Ali Gholizadeh",
    ],
  },
  {
    id: "nzl",
    code: "NZL",
    name: "Nova Zelândia",
    flag: "🇳🇿",
    players: [
      "Max Crocombe-Payne",
      "Alex Paulsen",
      "Michael Boxall",
      "Liberato Cacace",
      "Tim Payne",
      "Tyler Bindon",
      "Francis de Vries",
      "Finn Surman",
      "Joe Bell",
      "Sarpreet Singh",
      "Ryan Thomas",
      "Team Photo",
      "Matthew Garbett",
      "Marko Stamenić",
      "Ben Old",
      "Chris Wood",
      "Elijah Just",
      "Callum McCowatt",
      "Kosta Barbarouses",
    ],
  },

  /* ===== GRUPO H ===== */
  {
    id: "esp",
    code: "ESP",
    name: "Espanha",
    flag: "🇪🇸",
    players: [
      "Unai Simón",
      "Robin Le Normand",
      "Aymeric Laporte",
      "Dean Huijsen",
      "Pedro Porro",
      "Dani Carvajal",
      "Marc Cucurella",
      "Martin Zubimendi",
      "Rodri",
      "Pedri",
      "Fabián Ruiz",
      "Team Photo",
      "Mikel Merino",
      "Lamine Yamal",
      "Dani Olmo",
      "Nico Williams",
      "Ferran Torres",
      "Álvaro Morata",
      "Mikel Oyarzabal",
    ],
  },
  {
    id: "cpv",
    code: "CPV",
    name: "Cabo Verde",
    flag: "🇨🇻",
    players: [
      "Vozinha",
      "Logan Costa",
      "Pico",
      "Diney",
      "Steven Moreira",
      "Wagner Pina",
      "João Paulo",
      "Yannick Semedo",
      "Kevin Pina",
      "Patrick Andrade",
      "Jamiro Monteiro",
      "Team Photo",
      "Deroy Duarte",
      "Garry Rodrigues",
      "Jovane Cabral",
      "Ryan Mendes",
      "Dailon Livramento",
      "Willy Semedo",
      "Bebé",
    ],
  },
  {
    id: "ksa",
    code: "KSA",
    name: "Arábia Saudita",
    flag: "🇸🇦",
    players: [
      "Nawaf Alaqidi",
      "Abdulrahman Al-Sanbi",
      "Saud Abdulhamid",
      "Nawaf Boushal",
      "Jihad Thakri",
      "Moteb Al-Harbi",
      "Hassan Altambakti",
      "Musab Aljuwayr",
      "Ziyad Aljohani",
      "Abdullah Alkhaibari",
      "Nasser Aldawsari",
      "Team Photo",
      "Saleh Abu Alshamat",
      "Marwan Alsahafi",
      "Salem Aldawsari",
      "Abdulrahman Al-Aboud",
      "Feras Albrikan",
      "Saleh Alshehri",
      "Abdullah Al-Hamdan",
    ],
  },
  {
    id: "uru",
    code: "URU",
    name: "Uruguai",
    flag: "🇺🇾",
    players: [
      "Sergio Rochet",
      "Santiago Mele",
      "Ronald Araujo",
      "José María Giménez",
      "Sebastian Caceres",
      "Mathias Olivera",
      "Guillermo Varela",
      "Nahitan Nandez",
      "Federico Valverde",
      "Giorgian De Arrascaeta",
      "Rodrigo Bentancur",
      "Team Photo",
      "Manuel Ugarte",
      "Nicolás de la Cruz",
      "Maxi Araujo",
      "Darwin Núñez",
      "Federico Viñas",
      "Rodrigo Aguirre",
      "Facundo Pellistri",
    ],
  },

  /* ===== GRUPO I ===== */
  {
    id: "fra",
    code: "FRA",
    name: "França",
    flag: "🇫🇷",
    players: [
      "Mike Maignan",
      "Theo Hernández",
      "William Saliba",
      "Jules Koundé",
      "Ibrahima Konaté",
      "Dayot Upamecano",
      "Lucas Digne",
      "Aurélien Tchouaméni",
      "Eduardo Camavinga",
      "Manu Koné",
      "Adrien Rabiot",
      "Team Photo",
      "Michael Olise",
      "Ousmane Dembélé",
      "Bradley Barcola",
      "Désiré Doué",
      "Kingsley Coman",
      "Hugo Ekitike",
      "Kylian Mbappé",
    ],
  },
  {
    id: "sen",
    code: "SEN",
    name: "Senegal",
    flag: "🇸🇳",
    players: [
      "Eduardo Mendy",
      "Yehvann Diouf",
      "Moussa Niakhaté",
      "Abdoulaye Seck",
      "Ismail Jakobs",
      "El Hadji Malick Diouf",
      "Kalidou Koulibaly",
      "Idrissa Gana Gueye",
      "Pape Matar Sarr",
      "Pape Gueye",
      "Habib Diarra",
      "Team Photo",
      "Lamine Camara",
      "Sadio Mane",
      "Ismaïla Sarr",
      "Boulaye Dia",
      "Iliman Ndiaye",
      "Nicolas Jackson",
      "Krepin Diatta",
    ],
  },
  {
    id: "irq",
    code: "IRQ",
    name: "Iraque",
    flag: "🇮🇶",
    players: [
      "Jalal Hassan",
      "Rebin Sulaka",
      "Hussein Ali",
      "Akam Hashem",
      "Merchas Doski",
      "Zaid Tahseen",
      "Manaf Younis",
      "Zidane Iqbal",
      "Amir Al-Ammari",
      "Ibrahim Bayesh",
      "Ali Jasim",
      "Team Photo",
      "Youssef Amyn",
      "Aimar Sher",
      "Marko Farji",
      "Osama Rashid",
      "Ali Al-Hamadi",
      "Aymen Hussein",
      "Mohanad Ali",
    ],
  },
  {
    id: "nor",
    code: "NOR",
    name: "Noruega",
    flag: "🇳🇴",
    players: [
      "Ørjan Nyland",
      "Julian Ryerson",
      "Leo Østigård",
      "Kristoffer Ajer",
      "Marcus Holmgren Pedersen",
      "David Møller Wolfe",
      "Torbjørn Heggem",
      "Morten Thorsby",
      "Martin Ødegaard",
      "Sander Berge",
      "Andreas Schjelderup",
      "Team Photo",
      "Patrick Berg",
      "Erling Haaland",
      "Alexander Sørloth",
      "Aron Dønnum",
      "Jørgen Strand Larsen",
      "Antonio Nusa",
      "Oscar Bobb",
    ],
  },

  /* ===== GRUPO J ===== */
  {
    id: "arg",
    code: "ARG",
    name: "Argentina",
    flag: "🇦🇷",
    players: [
      "Emiliano Martínez",
      "Nahuel Molina",
      "Cristian Romero",
      "Nicolás Otamendi",
      "Nicolás Tagliafico",
      "Leonardo Balerdi",
      "Enzo Fernández",
      "Alexis Mac Allister",
      "Rodrigo De Paul",
      "Exequiel Palacios",
      "Leandro Paredes",
      "Team Photo",
      "Nico Paz",
      "Franco Mastantuono",
      "Nico González",
      "Lionel Messi",
      "Lautaro Martínez",
      "Julián Álvarez",
      "Giuliano Simeone",
    ],
  },
  {
    id: "alg",
    code: "ALG",
    name: "Argélia",
    flag: "🇩🇿",
    players: [
      "Alexis Guendouz",
      "Ramy Bensebaini",
      "Youcef Atal",
      "Rayan Aït-Nouri",
      "Mohamed Amine Tougai",
      "Aïssa Mandi",
      "Ismael Bennacer",
      "Houssem Aouar",
      "Hicham Boudaoui",
      "Ramiz Zerrouki",
      "Nabil Bentaleb",
      "Team Photo",
      "Farés Chaibi",
      "Riyad Mahrez",
      "Said Benrahma",
      "Anis Hadj Moussa",
      "Amine Gouiri",
      "Baghdad Bounedjah",
      "Mohammed Amoura",
    ],
  },
  {
    id: "aut",
    code: "AUT",
    name: "Áustria",
    flag: "🇦🇹",
    players: [
      "Alexander Schlager",
      "Patrick Pentz",
      "David Alaba",
      "Kevin Danso",
      "Philipp Lienhart",
      "Stefan Posch",
      "Phillipp Mwene",
      "Alexander Prass",
      "Xaver Schlager",
      "Marcel Sabitzer",
      "Konrad Laimer",
      "Team Photo",
      "Florian Grillitsch",
      "Nicolas Seiwald",
      "Romano Schmid",
      "Patrick Wimmer",
      "Christoph Baumgartner",
      "Michael Gregoritsch",
      "Marko Arnautović",
    ],
  },
  {
    id: "jor",
    code: "JOR",
    name: "Jordânia",
    flag: "🇯🇴",
    players: [
      "Yazeed Abulaila",
      "Ihsan Haddad",
      "Mohammad Abu Hashish",
      "Yazan Al-Arab",
      "Abdallah Nasib",
      "Saleem Obaid",
      "Mohammad Abualnadi",
      "Ibrahim Saadeh",
      "Nizar Al-Rashdan",
      "Noor Al-Rawabdeh",
      "Mohannad Abu Taha",
      "Team Photo",
      "Amer Jamous",
      "Musa Al-Taamari",
      "Yazan Al-Naimat",
      "Mahmoud Al-Mardi",
      "Ali Olwan",
      "Mohammad Abu Zrayq",
      "Ibrahim Sabra",
    ],
  },

  /* ===== GRUPO K ===== */
  {
    id: "por",
    code: "POR",
    name: "Portugal",
    flag: "🇵🇹",
    players: [
      "Diogo Costa",
      "Jose Sa",
      "Ruben Dias",
      "João Cancelo",
      "Diogo Dalot",
      "Nuno Mendes",
      "Gonçalo Inácio",
      "Bernardo Silva",
      "Bruno Fernandes",
      "Ruben Neves",
      "Vitinha",
      "Team Photo",
      "João Neves",
      "Cristiano Ronaldo",
      "Francisco Trincão",
      "João Felix",
      "Gonçalo Ramos",
      "Pedro Neto",
      "Rafael Leão",
    ],
  },
  {
    id: "cod",
    code: "COD",
    name: "República Democrática do Congo",
    flag: "🇨🇩",
    players: [
      "Lionel Mpasi",
      "Aaron Wan-Bissaka",
      "Axel Tuanzebe",
      "Arthur Masuaku",
      "Chancel Mbemba",
      "Joris Kayembe",
      "Charles Pickel",
      "Ngal'ayel Mukau",
      "Edo Kayembe",
      "Samuel Moutoussamy",
      "Noah Sadiki",
      "Team Photo",
      "Théo Bongonda",
      "Meschack Elia",
      "Yoane Wissa",
      "Brian Cipenga",
      "Fiston Mayele",
      "Cédric Bakambu",
      "Nathanaël Mbuku",
    ],
  },
  {
    id: "uzb",
    code: "UZB",
    name: "Uzbequistão",
    flag: "🇺🇿",
    players: [
      "Utkir Yusupov",
      "Farrukh Sayfiev",
      "Sherzod Nasrullaev",
      "Umar Eshmurodov",
      "Husniddin Aliqulov",
      "Rustam Ashurmatov",
      "Khojakbar Alijonov",
      "Abdukodir Khusanov",
      "Odiljon Hamrobekov",
      "Otabek Shukurov",
      "Jamshid Iskanderov",
      "Team Photo",
      "Azizbek Turgunboev",
      "Khojimat Erkinov",
      "Eldor Shomurodov",
      "Oston Urunov",
      "Jaloliddin Masharipov",
      "Igor Sergeev",
      "Abbosbek Fayzullaev",
    ],
  },
  {
    id: "col",
    code: "COL",
    name: "Colômbia",
    flag: "🇨🇴",
    players: [
      "Camilo Vargas",
      "David Ospina",
      "Dávinson Sánchez",
      "Yerry Mina",
      "Daniel Muñoz",
      "Johan Mojica",
      "Jhon Lucumí",
      "Santiago Arias",
      "Jefferson Lerma",
      "Kevin Castaño",
      "Richard Rios",
      "Team Photo",
      "James Rodríguez",
      "Juan Fernando Quintero",
      "Jorge Carrascal",
      "Jhon Arias",
      "Jhon Córdoba",
      "Luis Suárez",
      "Luis Diaz",
    ],
  },

  /* ===== GRUPO L ===== */
  {
    id: "eng",
    code: "ENG",
    name: "Inglaterra",
    flag: "🏴\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
    players: [
      "Jordan Pickford",
      "John Stones",
      "Marc Guéhi",
      "Ezri Konsa",
      "Trent Alexander-Arnold",
      "Reece James",
      "Dan Burn",
      "Jordan Henderson",
      "Declan Rice",
      "Jude Bellingham",
      "Cole Palmer",
      "Team Photo",
      "Morgan Rogers",
      "Anthony Gordon",
      "Phil Foden",
      "Bukayo Saka",
      "Harry Kane",
      "Marcus Rashford",
      "Ollie Watkins",
    ],
  },
  {
    id: "cro",
    code: "CRO",
    name: "Croácia",
    flag: "🇭🇷",
    players: [
      "Dominik Livaković",
      "Duje Ćaleta-Car",
      "Joško Gvardiol",
      "Josip Stanišić",
      "Luka Vušković",
      "Josip Šutalo",
      "Kristijan Jakić",
      "Luka Modrić",
      "Mateo Kovačić",
      "Martin Baturina",
      "Lovro Majer",
      "Team Photo",
      "Mario Pašalić",
      "Petar Sučić",
      "Ivan Perišić",
      "Marco Pašalić",
      "Ante Budimir",
      "Andrej Kramarić",
      "Franjo Ivanović",
    ],
  },
  {
    id: "gha",
    code: "GHA",
    name: "Gana",
    flag: "🇬🇭",
    players: [
      "Lawrence Ati Zigi",
      "Tariq Lamptey",
      "Mohammed Salisu",
      "Alidu Seidu",
      "Alexander Djiku",
      "Gideon Mensah",
      "Caleb Yirenkyi",
      "Abdul Fatawu Issahaku",
      "Thomas Partey",
      "Salis Abdul Samed",
      "Kamaldeen Sulemana",
      "Team Photo",
      "Mohammed Kudus",
      "Iñaki Williams",
      "Jordan Ayew",
      "André Ayew",
      "Joseph Paintsil",
      "Osman Bukari",
      "Antoine Semenyo",
    ],
  },
  {
    id: "pan",
    code: "PAN",
    name: "Panamá",
    flag: "🇵🇦",
    players: [
      "Orlando Mosquera",
      "Luis Mejía",
      "Fidel Escobar",
      "Andrés Andrade",
      "Michael Amir Murillo",
      "Eric Davis",
      "José Córdoba",
      "César Blackman",
      "Cristian Martínez",
      "Aníbal Godoy",
      "Adalberto Carrasquilla",
      "Team Photo",
      "Édgar Bárcenas",
      "Carlos Harvey",
      "Ismael Díaz",
      "José Fajardo",
      "Cecilio Waterman",
      "José Luis Rodríguez",
      "Alberto Quintero",
    ],
  },
];

/* monta as 20 figurinhas de cada país */
function buildCountrySection(country) {
  const stickers = [];
  stickers.push({ code: `${country.code}-1`, name: "Escudo" });

  const knownPlayers = country.players || [];
  for (let i = 2; i <= 19; i++) {
    const idx = i - 2;
    const playerName = knownPlayers[idx] || `Jogador ${String(i).padStart(2, "0")}`;
    stickers.push({ code: `${country.code}-${i}`, name: playerName });
  }
  const photoName = knownPlayers[18] || "Time Oficial";
  stickers.push({ code: `${country.code}-20`, name: photoName });

  return {
    id: country.id,
    code: country.code,
    name: country.name,
    longName: country.name,
    flag: country.flag,
    stickers,
  };
}

const ALBUM = {
  totalStickers: 0,
  sections: [
    COVER_SECTION,
    FWC_SECTION,
    ...COUNTRIES.map(buildCountrySection),
  ],
};

ALBUM.totalStickers = ALBUM.sections.reduce(
  (sum, s) => sum + s.stickers.length,
  0
);
